# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "OFF")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "OFF")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "OFF")
SET(CPACK_BINARY_STGZ "ON")
SET(CPACK_BINARY_TBZ2 "OFF")
SET(CPACK_BINARY_TGZ "ON")
SET(CPACK_BINARY_TZ "ON")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "TBZ2")
SET(CPACK_IGNORE_FILES "~;.swp;\\.hg;\\.git;\\.orig$;\\.exe$;\\.a$;\\.so$;\\.dylib$;\\.dll$;\\.ppu$;\\.o$;\\.cxx$;\\.hi$;\\.xcf$;\\.svg$;\\.svgz$;\\.psd$;\\.sifz$;\\.core$;\\.layout$;\\.db$;\\.dof$;\\.or$;\\.stackdump$;\\.zip$;\\.gz$;\\.bz2$;\\.tmp$;hwconsts\\.cpp$;config\\.inc$;hwengine\\.desktop$;Info\\.plist$;moc_.*\\.cxx_parameters;\\.qrc.depends$;\\.qm$;Makefile$;Doxyfile;CMakeFiles;[dD]ebug$;[rR]elease$;CPack;cmake_install\\.cmake$;cmake_uninstall\\.cmake$;CMakeCache\\.txt$;build_windows_.*\\.bat$;arch\\.c$;^/home/tomek/hg/hedgewars/myHedgewarsBranch/misc/winutils/bin;^/home/tomek/hg/hedgewars/myHedgewarsBranch/project_files/promotional_art;^/home/tomek/hg/hedgewars/myHedgewarsBranch/project_files/AudioMono;^/home/tomek/hg/hedgewars/myHedgewarsBranch/project_files/HedgewarsMobile;^/home/tomek/hg/hedgewars/myHedgewarsBranch/tools/templates;^/home/tomek/hg/hedgewars/myHedgewarsBranch/tools/drawMapTest;^/home/tomek/hg/hedgewars/myHedgewarsBranch/doc;^/home/tomek/hg/hedgewars/myHedgewarsBranch/tmp;^/home/tomek/hg/hedgewars/myHedgewarsBranch/utils;^/home/tomek/hg/hedgewars/myHedgewarsBranch/share/hedgewars/Data/Maps/test;^/home/tomek/hg/hedgewars/myHedgewarsBranch/install_manifest.txt;^/home/tomek/hg/hedgewars/myHedgewarsBranch/CMakeCache.txt;^/home/tomek/hg/hedgewars/myHedgewarsBranch/hedgewars\\.")
SET(CPACK_INSTALLED_DIRECTORIES "/home/tomek/hg/hedgewars/myHedgewarsBranch;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/home/tomek/games")
SET(CPACK_MODULE_PATH "/home/tomek/hg/hedgewars/myHedgewarsBranch/cmake_modules")
SET(CPACK_NSIS_DISPLAY_NAME "Hedgewars 0.9.23-rGIT")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "Hedgewars 0.9.23-rGIT")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/tomek/hg/hedgewars/myHedgewarsBranch/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Hedgewars, a free turn-based strategy game")
SET(CPACK_PACKAGE_EXECUTABLES "hedgewars;Hedgewars")
SET(CPACK_PACKAGE_FILE_NAME "hedgewars-src-0.9.23-rGIT")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "Hedgewars 0.9.23-rGIT")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Hedgewars 0.9.23-rGIT")
SET(CPACK_PACKAGE_NAME "hedgewars")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Hedgewars Project")
SET(CPACK_PACKAGE_VERSION "0.9.23")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "9")
SET(CPACK_PACKAGE_VERSION_PATCH "23")
SET(CPACK_RESOURCE_FILE_LICENSE "/home/tomek/hg/hedgewars/myHedgewarsBranch/COPYING")
SET(CPACK_RESOURCE_FILE_README "/usr/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TBZ2")
SET(CPACK_SOURCE_IGNORE_FILES "~;.swp;\\.hg;\\.git;\\.orig$;\\.exe$;\\.a$;\\.so$;\\.dylib$;\\.dll$;\\.ppu$;\\.o$;\\.cxx$;\\.hi$;\\.xcf$;\\.svg$;\\.svgz$;\\.psd$;\\.sifz$;\\.core$;\\.layout$;\\.db$;\\.dof$;\\.or$;\\.stackdump$;\\.zip$;\\.gz$;\\.bz2$;\\.tmp$;hwconsts\\.cpp$;config\\.inc$;hwengine\\.desktop$;Info\\.plist$;moc_.*\\.cxx_parameters;\\.qrc.depends$;\\.qm$;Makefile$;Doxyfile;CMakeFiles;[dD]ebug$;[rR]elease$;CPack;cmake_install\\.cmake$;cmake_uninstall\\.cmake$;CMakeCache\\.txt$;build_windows_.*\\.bat$;arch\\.c$;^/home/tomek/hg/hedgewars/myHedgewarsBranch/misc/winutils/bin;^/home/tomek/hg/hedgewars/myHedgewarsBranch/project_files/promotional_art;^/home/tomek/hg/hedgewars/myHedgewarsBranch/project_files/AudioMono;^/home/tomek/hg/hedgewars/myHedgewarsBranch/project_files/HedgewarsMobile;^/home/tomek/hg/hedgewars/myHedgewarsBranch/tools/templates;^/home/tomek/hg/hedgewars/myHedgewarsBranch/tools/drawMapTest;^/home/tomek/hg/hedgewars/myHedgewarsBranch/doc;^/home/tomek/hg/hedgewars/myHedgewarsBranch/tmp;^/home/tomek/hg/hedgewars/myHedgewarsBranch/utils;^/home/tomek/hg/hedgewars/myHedgewarsBranch/share/hedgewars/Data/Maps/test;^/home/tomek/hg/hedgewars/myHedgewarsBranch/install_manifest.txt;^/home/tomek/hg/hedgewars/myHedgewarsBranch/CMakeCache.txt;^/home/tomek/hg/hedgewars/myHedgewarsBranch/hedgewars\\.")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/tomek/hg/hedgewars/myHedgewarsBranch;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/tomek/hg/hedgewars/myHedgewarsBranch/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "hedgewars-src-0.9.23-rGIT")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux-Source")
